- name: Install docker on aws ec2
  hosts: aws
  become: true
  tasks:
    - name: Updata packages
      ansible.builtin.apt:
        update_cache: yes
        
    - name: install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
    
    - name: Add user ubunto in docker
      user:
        name: ubuntu
        groups: docker
        append: yes