name: Test and merge dev to main branch

on:
  push:
    branches:
      - dev

jobs:
  test_before_merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
        
      - name: Build and run docker-compose
        run : |
            docker-compose up -d --build
            sleep 10
            docker ps

      - name: Run helth check
        run: |
           echo "Waiting for the app to be available..."
           sleep 5
           curl -f http://localhost:5000 || exit 1

  merge:
    needs: test_before_merge
    runs-on: ubuntu-latest

    steps:
      - name: Merge dev in main
        uses: actions/checkout@v4
        
      - name: Mege dev -> main
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "github-actions"
          git fetch origin
          git checkout main
          git pull origin main
          git merge --no-ff dev -m "Auto-merge dev into main"
          git push origin main
