name: Deploy-to-AWS-EC2

on:
  push:
    branches:
        - main #Запускать при пуше в main

jobs:
  test_before_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build and run docker-compose
        run : |
            docker-compose up -d --build
            sleep 10
            docker ps

      - name: Run helth check
        run: |
           echo "Waiting for the app to be available..."
           sleep 5
           curl -f http://localhost:5000 || exit 1
  
  deploy:
    needs: test_before_deploy
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v4 #clon repo

      - name: SSH Connection
        run: |
            echo "${{ secrets.EC2_KEY }}" > private_key.pem
            chmod 400 private_key.pem
            
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
           rm -rf app  # Очистка старой версии
             git clone https://github.com/andrii-br/first-ci app
             cd app
             docker-compose down  # Остановка предыдущей версии
             docker-compose up -d  # Запуск в фоновом режиме
             docker ps -a  # Проверка запущенных контейнеров
          EOF
        
          
